all: hello

hello: hello.o
	g++ -g -o hello hello.o


hello.o: hello.cpp
	g++ -g -c hello.cpp

3questions: 3questions.o
	g++ -g -o 3questions 3questions.o

3questions.o: 3questions.cpp
	g++ -g -c 3questions.cpp